# Generated by Django 2.2.17 on 2020-12-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='extra_avatar',
        ),
    ]
